"""
build_presentation.py — builds the .pptx deck (~10 min, ~11 slides)
on pattern separation in the dentate gyrus (DG).

Audience: mixed (ML + some neuro).
Figures: reused from the repo (freq_audit.png, bifurcation_K.png,
visualize_dg_circuit.png, visualize_dg_neurons.png).

Run:
    snn_sep_venv/Scripts/python.exe prezentacja/build_presentation.py
Output: prezentacja/prezentacja_DG.pptx
"""

import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.dml.color import RGBColor
from PIL import Image

# ── Paths ─────────────────────────────────────────────────────────────────────
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
def img(name):
    return os.path.join(ROOT, name)
def figp(name):
    """English figures generated by make_en_figures.py (live in prezentacja/)."""
    return os.path.join(HERE, name)

# ── Palette (consistent with the app) ─────────────────────────────────────────
C_GC   = RGBColor(0x15, 0x65, 0xC0)   # blue (GC / accent)
C_FS   = RGBColor(0xC6, 0x28, 0x28)   # red (inhibition)
C_HMC  = RGBColor(0xE6, 0x51, 0x00)   # orange (mossy)
C_PP   = RGBColor(0x2E, 0x7D, 0x32)   # green (excitation)
C_DARK = RGBColor(0x21, 0x21, 0x21)
C_GREY = RGBColor(0x60, 0x60, 0x60)
C_BG   = RGBColor(0xF5, 0xF7, 0xFA)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)

FONT = "Calibri"

prs = Presentation()
prs.slide_width  = Inches(13.333)   # 16:9
prs.slide_height = Inches(7.5)
SW, SH = prs.slide_width, prs.slide_height
BLANK = prs.slide_layouts[6]


# ── Helpers ───────────────────────────────────────────────────────────────────
def add_slide():
    s = prs.slides.add_slide(BLANK)
    s.background.fill.solid()
    s.background.fill.fore_color.rgb = C_BG
    return s


def textbox(slide, l, t, w, h, anchor=MSO_ANCHOR.TOP):
    tb = slide.shapes.add_textbox(l, t, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    return tf


def set_run(r, text, size, bold=False, color=C_DARK, italic=False):
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.italic = italic
    r.font.color.rgb = color
    r.font.name = FONT


def accent_bar(slide, color=C_GC):
    bar = slide.shapes.add_shape(1, Inches(0), Inches(0), SW, Inches(0.14))
    bar.fill.solid(); bar.fill.fore_color.rgb = color
    bar.line.fill.background()
    return bar


def title_block(slide, title, color=C_GC):
    accent_bar(slide, color)
    tf = textbox(slide, Inches(0.55), Inches(0.30), Inches(12.2), Inches(1.0))
    p = tf.paragraphs[0]
    set_run(p.add_run(), title, 30, bold=True, color=C_DARK)
    return tf


def bullets(slide, items, l=Inches(0.6), t=Inches(1.5),
            w=Inches(6.4), h=Inches(5.4), size=17, gap=8):
    """items: list of (text, level, color, bold)."""
    tf = textbox(slide, l, t, w, h)
    first = True
    for it in items:
        text = it[0]; level = it[1] if len(it) > 1 else 0
        color = it[2] if len(it) > 2 else C_DARK
        bold = it[3] if len(it) > 3 else False
        p = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.level = level
        p.space_after = Pt(gap)
        bullet = "•  " if level == 0 else "–  "
        set_run(p.add_run(), bullet + text, size - level * 1, bold=bold,
                color=color)
    return tf


def picture_fit(slide, path, box_l, box_t, box_w, box_h):
    """Insert image preserving aspect ratio, fitted into the box."""
    with Image.open(path) as im:
        iw, ih = im.size
    ar = iw / ih
    box_ar = box_w / box_h
    if ar > box_ar:
        w = box_w; h = Emu(int(box_w / ar))
    else:
        h = box_h; w = Emu(int(box_h * ar))
    l = box_l + Emu(int((box_w - w) / 2))
    t = box_t + Emu(int((box_h - h) / 2))
    return slide.shapes.add_picture(path, l, t, w, h)


def caption(slide, text, l, t, w, color=C_GREY, size=11):
    tf = textbox(slide, l, t, w, Inches(0.5))
    p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
    set_run(p.add_run(), text, size, italic=True, color=color)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 1 — Title
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
panel = s.shapes.add_shape(1, Inches(0), Inches(2.3), SW, Inches(2.9))
panel.fill.solid(); panel.fill.fore_color.rgb = C_GC; panel.line.fill.background()

tf = textbox(s, Inches(0.7), Inches(2.55), Inches(12.0), Inches(1.6))
set_run(tf.paragraphs[0].add_run(),
        "Pattern Separation in the Dentate Gyrus (DG)", 40, bold=True, color=WHITE)
p = tf.add_paragraph()
set_run(p.add_run(),
        "Simulating the biological mechanisms of sparse coding and inhibition",
        20, color=WHITE)

tf2 = textbox(s, Inches(0.7), Inches(5.45), Inches(12.0), Inches(1.0))
set_run(tf2.paragraphs[0].add_run(),
        "Tool: Brian2 + Streamlit  ·  Jakub Caputa  ·  2026-06-25",
        16, color=C_GREY)
p = tf2.add_paragraph()
set_run(p.add_run(),
        "10 min: 3 mechanisms → live demo → directions for the PhD",
        14, italic=True, color=C_GREY)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 2 — Problem: why separate patterns
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "The problem: why separate patterns?")
bullets(s, [
    ("The hippocampus must store SIMILAR episodes without confusing them",
     0, C_DARK, True),
    ("e.g. \"where did I park today\" vs yesterday — almost the same cues", 1),
    ("DG = the first stage: it takes cortical input (perforant path, PP)", 0),
    ("and PUSHES similar patterns apart before they reach CA3 (associative memory)",
     1),
    ("Metric: Pearson correlation of inputs R_in vs outputs R_out", 0, C_DARK, True),
    ("separation = R_out < R_in  (decorrelation > 0)", 1, C_GC),
    ("ML analogy: sparse coding / dimensional expansion", 0, C_PP, True),
    ("fewer overlapping representations = less memory interference", 1),
], w=Inches(7.2))

box = s.shapes.add_shape(1, Inches(8.2), Inches(2.0), Inches(4.5), Inches(3.6))
box.fill.solid(); box.fill.fore_color.rgb = WHITE
box.line.color.rgb = C_GC; box.line.width = Pt(1.5)
tf = box.text_frame; tf.word_wrap = True
tf.vertical_anchor = MSO_ANCHOR.MIDDLE
set_run(tf.paragraphs[0].add_run(), "Similar inputs", 16, bold=True, color=C_GREY)
p = tf.add_paragraph()
set_run(p.add_run(), "R_in ≈ 0.75", 26, bold=True, color=C_FS)
p = tf.add_paragraph()
set_run(p.add_run(), "↓  DG  ↓", 22, bold=True, color=C_DARK)
p = tf.add_paragraph()
set_run(p.add_run(), "Pushed-apart outputs", 16, bold=True, color=C_GREY)
p = tf.add_paragraph()
set_run(p.add_run(), "R_out ≈ 0.33", 26, bold=True, color=C_GC)
for par in tf.paragraphs:
    par.alignment = PP_ALIGN.CENTER


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 3 — Real DG circuit (placeholder to paste a figure from a publication)
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "The dentate gyrus circuit (biology)", C_PP)
# Empty framed placeholder — paste a circuit figure from a publication here.
ph = s.shapes.add_shape(1, Inches(1.4), Inches(1.7), Inches(10.5), Inches(4.7))
ph.fill.solid(); ph.fill.fore_color.rgb = WHITE
ph.line.color.rgb = C_GREY; ph.line.width = Pt(1.25)
tfp = ph.text_frame; tfp.word_wrap = True; tfp.vertical_anchor = MSO_ANCHOR.MIDDLE
p = tfp.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
set_run(p.add_run(), "[ paste circuit figure from a publication here ]",
        18, italic=True, color=C_GREY)
caption(s, "biological reference — to be replaced with a published DG circuit diagram",
        Inches(1.4), Inches(6.55), Inches(10.5))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 4 — DG circuit (what we model)
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "The DG circuit — what we model")
bullets(s, [
    ("Four populations:", 0, C_DARK, True),
    ("PP — input (perforant path) from entorhinal cortex", 1, C_PP),
    ("GC — granule cells, excitatory → DG OUTPUT", 1, C_GC),
    ("FS — fast-spiking interneurons, INHIBITORY", 1, C_FS),
    ("HMC — hilar mossy cells, excitatory (modulation)", 1, C_HMC),
    ("Two kinds of inhibition:", 0, C_DARK, True),
    ("feedforward  PP→FS→GC  (inhibit before GC reacts)", 1),
    ("feedback  GC→FS→GC  (inhibit after GC has fired)", 1),
    ("GC ~10× more numerous than FS, code sparsely;", 0),
    ("FS are fast — they decide WHEN a GC is allowed to fire", 1),
], l=Inches(0.5), t=Inches(1.45), w=Inches(5.6), size=15)
picture_fit(s, figp("fig_network_en.png"),
            Inches(6.3), Inches(1.35), Inches(6.7), Inches(5.6))
caption(s, "Small example so connections stay visible (each dot = neuron, line = synapse)",
        Inches(6.3), Inches(6.95), Inches(6.7))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 4 — How we model a single neuron
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "How we model a single neuron")
bullets(s, [
    ("Izhikevich model — 2 differential equations", 0, C_DARK, True),
    ("realistic firing patterns (spiking) at low cost", 1),
    ("trade-off: richer than LIF, cheaper than Hodgkin–Huxley", 1),
    ("Input = synaptic conductances", 0, C_DARK, True),
    ("g_ex — excitation (AMPA), RAISES the voltage V", 1, C_PP),
    ("g_in — inhibition (GABA-A), LOWERS the voltage V", 1, C_HMC),
    ("A neuron fires when the net drive crosses threshold", 0),
    ("The tool also has a simple LIF mode (1 neuron) — pure intuition:", 0, C_DARK, True),
    ("even near-identical inputs give different spike times → decorrelation",
     1, C_GC),
], w=Inches(11.8), size=18)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 5 — Mechanism 1: sparse coding (frequencies)
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Mechanism 1: sparse coding", C_PP)
bullets(s, [
    ("PP input = 40 fibers × 10 Hz = 400 Hz (aggregate)", 0, C_DARK, True),
    ("a single physiological fiber ~10 Hz", 1),
    ("Drive calibration:", 0, C_DARK, True),
    ("400 Hz → GC ~6 Hz  (DG target: 1–10 Hz) ✓", 1, C_PP),
    ("600 Hz → GC ~16 Hz  — too dense ✗", 1, C_FS),
    ("Sparseness is not a side effect — it is a PREREQUISITE for separation:",
     0, C_DARK, True),
    ("fewer active GC = less overlap between patterns", 1, C_GC),
], l=Inches(0.5), t=Inches(1.45), w=Inches(5.3), size=15)
picture_fit(s, figp("fig_freq_en.png"),
            Inches(5.9), Inches(1.4), Inches(7.1), Inches(5.3))
caption(s, "GC output vs input strength — operating point set inside the \"DG target\"",
        Inches(5.9), Inches(6.8), Inches(7.1))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 6 — Mechanism 2: excitability (K_tonic)
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Mechanism 2: excitability = threshold (K_tonic)", C_HMC)
bullets(s, [
    ("K_tonic = tonic GABA inhibition (background)", 0, C_DARK, True),
    ("it raises the firing threshold:  G_crit = 4 + K", 1, C_HMC),
    ("derived analytically, confirmed in simulation (to 0.1 mV)", 1),
    ("GC / HMC:  K=10 → threshold 14 mV", 0, C_GC, True),
    ("hard to excite → fire rarely", 1),
    ("FS:  K=5 → threshold 9 mV", 0, C_FS, True),
    ("easy to excite → gamma 30–100 Hz", 1),
    ("One parameter tunes \"how eagerly a population fires\"", 0, C_DARK, True),
], l=Inches(0.5), t=Inches(1.45), w=Inches(5.3), size=15)
picture_fit(s, figp("fig_bifurcation_en.png"),
            Inches(5.9), Inches(1.5), Inches(7.1), Inches(5.0))
caption(s, "K shifts the f–I curve and the G_crit threshold — linearly and predictably",
        Inches(5.9), Inches(6.6), Inches(7.1))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 7 — Mechanism 3: inhibition creates separation
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Mechanism 3: inhibition CREATES separation", C_FS)
bullets(s, [
    ("No inhibition: GC fire densely and similarly → weak decorrelation",
     0, C_FS, True),
    ("FF + FB: FS clamps the GC — only the most strongly driven GC fire",
     0, C_GC, True),
    ("→ patterns drift apart", 1, C_GC),
    ("Decorrelation grows: baseline +0.15 → full circuit +0.42", 0, C_DARK, True),
    ("Mossy cells: silent by default (sparse GC give them no drive)", 0, C_HMC),
    ("they can be revived → GC re-excitation vs stronger inhibition", 1, C_HMC),
], l=Inches(0.5), t=Inches(1.45), w=Inches(5.4), size=14)
picture_fit(s, figp("fig_circuit_en.png"),
            Inches(6.0), Inches(1.4), Inches(7.0), Inches(5.3))
caption(s, "baseline → FF → FB → full circuit: decorrelation grows with inhibition",
        Inches(6.0), Inches(6.8), Inches(7.0))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE — Result: pattern capacity (mean correlation vs number of patterns)
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Result: separation holds across many patterns", C_GC)
bullets(s, [
    ("Same circuit, growing number of input patterns (2 → 12)", 0, C_DARK, True),
    ("Input patterns stay similar:", 0),
    ("R_in ≈ 0.75 regardless of count", 1, C_GREY),
    ("GC output stays decorrelated:", 0),
    ("R_out ≈ 0.18 — flat as patterns are added", 1, C_GC),
    ("The green band = separation the DG provides", 0, C_PP, True),
    ("Capacity reading: the mechanism does not collapse as load grows", 0,
     C_DARK, True),
    ("(no learning here — a feedforward separation limit, not a storage limit)",
     1, C_GREY),
], l=Inches(0.5), t=Inches(1.5), w=Inches(5.1), size=15)
picture_fit(s, figp("fig_capacity_en.png"),
            Inches(5.7), Inches(1.5), Inches(7.3), Inches(5.2))
caption(s, "mean pairwise correlation vs number of patterns (R_in grey, R_out blue)",
        Inches(5.7), Inches(6.75), Inches(7.3))


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE — The tool (Streamlit) + observability
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "The tool: interactive simulation (Streamlit)")
bullets(s, [
    ("interactive_dg.py — all mechanisms in one place, on sliders, live",
     0, C_DARK, True),
    ("Emphasis on OBSERVABILITY — you can see what happens:", 0, C_DARK, True),
    ("firing of every cell type with a physiological-range flag", 1),
    ("live circuit schematic — arrow thickness = measured flow", 1),
    ("GC \"voltage budget\": what EXCITES (PP green, HMC orange),", 1),
    ("                              what INHIBITS (FS purple)", 1),
    ("Two modes: single neuron (LIF) and full population (Izhikevich)", 0),
    ("→  on to the live DEMO", 0, C_GC, True),
], w=Inches(11.8), size=18)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 9 — Demo plan
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Demo — 5 scenarios across parameters", C_GC)
bullets(s, [
    ("A · Starting point — full circuit", 0, C_DARK, True),
    ("sparse GC, FS in gamma, decorrelation > 0", 1),
    ("B · Role of inhibition — uncheck Feedforward + Feedback", 0, C_FS, True),
    ("GC become dense, the purple field vanishes, separation drops", 1),
    ("C · Excitability — K_GC 10 → 0 → 18", 0, C_HMC, True),
    ("0 = GC dense; 18 = GC go silent (threshold = 4+K)", 1),
    ("D · Mossy cells — W GC→HMC 1 → 14", 0, C_HMC, True),
    ("HMC come alive, the orange field grows (re-excitation)", 1),
    ("E · Drive — W PP→GC 4 → 9", 0, C_PP, True),
    ("overdrive, GC dense, separation drops", 1),
], w=Inches(11.8), size=17)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 10 — Why this matters for the PhD
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
title_block(s, "Why this matters for the PhD — from description to a thesis")
bullets(s, [
    ("Today: faithful simulation of biological mechanisms + an observable tool",
     0, C_GREY, True),
    ("Directions that turn the simulation into a scientific contribution:",
     0, C_DARK, True),
    ("DG as a biologically-motivated \"sparsifying\" layer before a classifier/memory",
     1, C_GC),
    ("→ does it improve discrimination of correlated / noisy inputs?", 2),
    ("Interference reduction: a DG front-end in continual learning (forgetting)",
     1, C_GC),
    ("Neuromorphic: tuning rules for sparse SNN layers (G_crit = 4+K) + energy",
     1, C_GC),
    ("Biological predictions: which motif (FF/FB/MC) dominates under which",
     1, C_GC),
    ("input statistics — comparable to data (Madar et al.)", 2),
    ("DG→CA3 extension: the separation vs completion trade-off (pattern completion)",
     1, C_GC),
], w=Inches(12.0), size=16)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE 11 — Summary
# ══════════════════════════════════════════════════════════════════════════════
s = add_slide()
panel = s.shapes.add_shape(1, Inches(0), Inches(0), SW, SH)
panel.fill.solid(); panel.fill.fore_color.rgb = C_GC; panel.line.fill.background()
tf = textbox(s, Inches(0.8), Inches(0.7), Inches(11.7), Inches(1.0))
set_run(tf.paragraphs[0].add_run(), "Summary", 34, bold=True, color=WHITE)
bullets_data = [
    "Three mechanisms: sparse coding · threshold/excitability (K) · inhibition (FF/FB/MC)",
    "Separation = an emergent effect of inhibition on a sparse, thresholded code",
    "The tool makes the mechanisms VISIBLE and CONTROLLABLE",
    "→ a foundation for the quantitative and applied questions of the PhD",
]
tf = textbox(s, Inches(0.9), Inches(2.1), Inches(11.5), Inches(4.5))
first = True
for b in bullets_data:
    p = tf.paragraphs[0] if first else tf.add_paragraph()
    first = False
    p.space_after = Pt(18)
    set_run(p.add_run(), "•  " + b, 22, color=WHITE, bold=True)
tf2 = textbox(s, Inches(0.9), Inches(6.4), Inches(11.5), Inches(0.8))
set_run(tf2.paragraphs[0].add_run(),
        "Thank you — questions / discussion", 18, italic=True, color=WHITE)


# ── Save ──────────────────────────────────────────────────────────────────────
out = os.path.join(HERE, "prezentacja_DG.pptx")
prs.save(out)
print(f"Saved: {out}  ({len(prs.slides._sldIdLst)} slides)")
